// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0awW7gQflvnxrZKgcbZWa7RYGJlTwJ_U',
    appId: '1:611105664531:web:f9d2d2f8303be379a559e6',
    messagingSenderId: '611105664531',
    projectId: 'lubustracker-bf90e',
    authDomain: 'lubustracker-bf90e.firebaseapp.com',
    storageBucket: 'lubustracker-bf90e.firebasestorage.app',
    measurementId: 'G-854Z91WC3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq0sNW7rivDaV455E-1fbmJCAPf-FFsJs',
    appId: '1:611105664531:android:f5734d2543cf29f0a559e6',
    messagingSenderId: '611105664531',
    projectId: 'lubustracker-bf90e',
    storageBucket: 'lubustracker-bf90e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNN_phIpmmdOq6W6GgfUylbQxWskn3YYI',
    appId: '1:611105664531:ios:625f87f065137298a559e6',
    messagingSenderId: '611105664531',
    projectId: 'lubustracker-bf90e',
    storageBucket: 'lubustracker-bf90e.firebasestorage.app',
    iosBundleId: 'com.example.luBusTracker',
  );
}
